services:
  apirest:
    build: apirest
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://hospital-db:1433;databaseName=Hospital;encrypt=false;trustServerCertificate=true
      DB_USER_NAME: sa
      DB_PASSWORD: Admin1234#
      
    restart: always
    depends_on:
      - hospital-db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 0s
  hospital-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA:Y
      - MSSQL_SA_PASSWORD:Admin1234#
      - MSSQL_DATA_DIR:/var/opt/mssql/data 
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT:1433
    restart: always
    volumes:
      - hospital-data:/var/opt/mssql
volumes:
  hospital-data: